### ISSUE TITLE
Unable Establish a secure connection to the server

### ISSUE THREAD

**Issue by idahoboi** [rbrasga/SPPD-Deck-Tracker#3]
Trying to get Deck Tracker setup for the first time on my new PC.  I've installed the certificate on local PC and Nox emulator. 
Proxy is setup, and app is running before I start SPPD.
Deck Tracker shows connected, but as soon as the start animation comes up for SPPD, it alerts me that it is unable to establish a secure connection to the server.  Clicking OK, results in the same error a few times, before it updates to say "cannot connect to server! Please check your internet connection".  Clicking retry does nothing.
SPPD runs without issue when Proxy is not set.
Did I miss a step?

**Comment by rbrasga** [comment]
Thanks for reminding me. I will be archiving this project shortly, and adding a note to the README that it doesn't work anymore.

Android security has come a long way in the four years since this project was created. So this project is no longer functional.
